### ISSUE TITLE
lilikoi.featuresSelection() does not work on the model dataset provided by the authors

### ISSUE THREAD

**Issue by luisebe** [lanagarmire/lilikoi2#6]
Dear authors, 
i have been trying to get through your example code including you model data. However, i have not been able to run lilikoi.featuresSelection(). I am using Windows 10 and R Version 4.2.2. I have already updated Java. 

Please see the error message below. 

> selected_Pathways_Weka= lilikoi.featuresSelection(PDSmatrix,threshold= 0.50,method="gain")
Error in training_diagnosis$Label - 1 : 
  non-numeric argument to binary operator

i am looking forward to hearing from you soon. 

Best, 
Dr. Luise Bellach

**Comment by lanagarmire** [comment]
Hi Dr Bellach,
Maybe  you can try something like: Metadata$Label <- as.factor(Metadata$Label)
to refactor the label column in your data.
At the same time, it would be helpful to provide more detailed sessionInfo or snippet of your sample data to help us repeat the error, because on our end with R 3.6 and 4.1 the code works fine.

**Comment by luisebe** [comment]
Great thank you, this worked well. 
I am currently expierencing difficulties with lilikoi.machine_learning() as the connection to the H2O now does not work (i cannot connect to their local host). I have already contacted the H2O support team - i hope i get answers soon so i can test out our vignette.
